### ISSUE TITLE
span start/end keeps increasing on https://swc.rs/playground

### ISSUE THREAD

**Issue by bartosz-k** [swc-project/swc-playground#1]
How to reproduce:

1. In "Output" pick "AST" view.
2. Type `1` in "Input" view.
3. Keep adding spaces after `1`.
4. Notice how span start/end properties keep going up.

Expected: don't artificially increase indexes on start/stop properties.

**Comment by g-plane** [comment]
Yes, I confirmed this bug, but I'm not sure if this bug is from SWC or not.

**Comment by kdy1** [comment]
This is because `Arc<SourceMap>` is reused if `swc::Compiler` is reused, and currently there's no js api to create new instance of `swc::Compiler`.
