### ISSUE TITLE
Wrong type displayed for dynamic Import?

### ISSUE THREAD

**Issue by ShayRubach** [swc-project/swc-playground#13]
Hey.
I have encountered a mismatch between the AST Explorer [Edit: [AST view in SWC's pg](https://play.swc.rs/)] and the library. My input is:
```javascript
let {hi, bye} = await import('./say.js');
```
The AST Explorer suggests that the `callee` lives inside of a node of type `Callee::Expr` (well `swc_ecma_ast::CallExp` in particular), see:
```javascript
"argument": {
      "type": "CallExpression",
      "span": {...},
      "callee": {
        "type": "Identifier",
        "span": {...},
        "value": "import",
        ...
      },
...
```
While the code shows it is actually a `swc_ecma_ast::Import`:
```javascript
CallExpr {
    span: Span { ... },
    callee: Import(Import { //<---------
        span: Span { ... }
    }),
    ....
}
```

Am I missing something, or it is an issue?
Thanks.

**Comment by g-plane** [comment]
AST explorer doesn't support SWC, so you're using different parsers, and different parsers can produce different ASTs.

**Comment by ShayRubach** [comment]
My terms were wrong. I was actually referring to the [AST view in SWC's playground](https://play.swc.rs/). This is were the correlation doesn't seem to be right.

**Comment by g-plane** [comment]
The playground is using an old version of SWC, so it produces different AST. I will update tomorrow.

**Comment by ShayRubach** [comment]
Btw, I don't think it is related, but for some reason `sym` is represented as `value` in SWC pg. See any `Ident` node for reference.

**Comment by ShayRubach** [comment]
@g-plane Hey again. The issue is back. Try this input for example
```javascript
Foo.bar(x).y
```
It produces an AST tree with a root `"type": "Module"` instead of a type `"type": "Script"` as the actual code suggests when printing the AST object (I know it is configurable when your create the parser but it is a different behavior than the one my code used to show, and I didn't change the code, only updated cargo).
Is there an option I can help with updating the SWC PG each time SWC is being updated? maybe work on a hook? I'll be more than happy to assist with a small guidance.

**Comment by g-plane** [comment]
I'm sorry that I can't understand your question...
