### ISSUE TITLE
[cargo install swc_cli@0.81.0] error on compile macbook air m1

### ISSUE THREAD

**Issue by RyanGuild** [swc-project/swc-playground#20]
Compiling swc v0.207.0
error[E0061]: this function takes 1 argument but 2 arguments were supplied
   --> /Users/ryanguild/.cargo/registry/src/github.com-1ecc6299db9ec823/swc-0.207.0/src/builder.rs:261:21
    |
261 |                       compat::es2017(
    |                       ^^^^^^^^^^^^^^ expected 1 argument
262 | /                         compat::es2017::Config {
263 | |                             async_to_generator: compat::es2017::async_to_generator::Config {
264 | |                                 ignore_function_name: assumptions.ignore_function_name,
265 | |                                 ignore_function_length: assumptions.ignore_function_length
266 | |                             },
267 | |                         },
    | |_________________________-
268 |                           self.unresolved_mark
    |                           -------------------- supplied 2 arguments

**Comment by g-plane** [comment]
It doesn't seem your problem is related to the playground.

**Comment by RyanGuild** [comment]
sorry
