### ISSUE TITLE
Compress options do not work

### ISSUE THREAD

**Issue by AHorak** [swc-project/swc-playground#27]
This is my Typescript input:

`
function test() : void {
	debugger;
	const x = 1;
	console.log("Test");
}
`

the Output to ES2015 is

`
function test() {
    debugger;
    const x = 1;
    console.log("Test");
}
`

so the options

drop_debugger
drop_console
const_to_let

are not applied

**Comment by g-plane** [comment]
I can't reproduce.

**Comment by AHorak** [comment]
Perhaps an Firefox Issue?

**Comment by g-plane** [comment]
You can provide a reproduction link by clicking the "Share" button.

**Comment by AHorak** [comment]
> You can provide a reproduction link by clicking the "Share" button.

https://play.swc.rs/?version=1.3.24&code=H4sIAAAAAAAAA0srzUsuyczPUyhJLS7R0FSwUijLz0xRqObl4kxJTSpNT08tsgayk%2FPziksUKhRsFQxh3PycVL2c%2FHQNpRCgTiVNoHAtLxcA%2B1eOlk8AAAA%3D&config=H4sIAAAAAAAAA3WUwZLbIAyG34XzHnbbaaezD9Bbn4EhRjhsMWKQ8MaTybtXxDa2k%2B0NfQgh%2FRJc1Qd16v2qkskEua5oimwu6l3xlIC67BOrF8UkyJlAcBPD5B5YXIC%2Bvb79kO2ASLA4vKjBR%2B%2BmGqzDIWUgqms5VAaILAbnIm4mZ%2Fxs1gkxgIlPtjakfWToIbe9DkMwiUCPZg8HqcITxgMqDFanjGlHo%2FXsMUq2K7NgrO7QQgM%2BQ8d%2BhM1FYohLJMnrwCycSt9X9WYIownFcHOCy10DuXAlZ%2FTE2pWa6aLZjA55zmgucfHyTmfgklukD%2FTxoMJfAMkyGKJoBthO3rmTHhw93RdePjppIE%2BNSne3rCL0Upv23rUCa9aQ2W9aZbClg1ph98j2yZK3oME5UXpjn5678xaqjiG6Zopmxm2jNpt6HaUjre1%2Fgr8lJ7734sgHw%2BdHRtNwwvAUYgA%2Bo33CIgPjI8wyuJf0SEu0ICKD3W0UqmYbUWk9ow71na0qyzjIGd0HPO1GN0mvq1zf5WUOJvZ1Oq%2BKMQUYIRxb%2B9%2FB%2BILJfWPt9DKT6wTCr7aWUuTBvb2uP8OtZoC2LBlI4%2B5%2FxE912%2F6ENQz9WRzno%2F8ApWhoc4kEAAA%3D

**Comment by g-plane** [comment]
You've set the "source type" option as "script", and SWC won't compress and mangle for script. To compress and mangle, switch "source type" option to "module".
