### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by AHorak** [swc-project/swc-playground#28]
Hello,

i saw an error handling in the source using the monaco feature of _setModelMarkers_:

```
useEffect(() => {
    const model = editorRef.current?.getModel()
    if (!monaco || !model) {
      return
    }

    if (output.err) {
      const markers = Array.from(parseSWCError(output.val)).map(
        ([_, message, line, col]): editor.IMarkerData => {
          const lineNumber = Number.parseInt(line!),
            column = Number.parseInt(col!)

          return {
            source: 'swc',
            message: message!,
            severity: monaco.MarkerSeverity.Error,
            startLineNumber: lineNumber,
            startColumn: column,
            endLineNumber: lineNumber,
            endColumn: column,
          }
        }
      )
      monaco.editor.setModelMarkers(model, 'swc', markers)
    }

    return () => monaco.editor.setModelMarkers(model, 'swc', [])
  }, [output, monaco])
```

But somehow this doesn't work. It looks like the structure of the error message in SWC has changed.

So the used regex does not apply:

```
const RE_SWC_ERROR = /error:\s(.+?)\n\s-->\s.+?:(\d+):(\d+)/gm

export function parseSWCError(message: string) {
  return message.matchAll(RE_SWC_ERROR)
}
```

https://play.swc.rs/?version=1.3.24&code=H4sIAAAAAAAAA0srzUsuyczPUyhJLS7RyEvMTdVUUKjm5eJMSU0qTU9PLbIGspPz84pLFCoUbBUMYdz8nFS9nPx0DaUQoD5NoGgtLxcAjeVwdUwAAAA%3D&config=H4sIAAAAAAAAA22TwXLjIAyG38XnHrad2T30AfbWZ2AICIcWEINEGk8m774iTm1s7w19CPFL%2FNyGTzLD%2B23IuhCUtqIpsb4O7wNPGcgUn3l4GZgEOR0I7hLoMgJLCtDbr9ffsh0QCZ4JL0P0ybupFTMYcwGitpZDNUJiCbhUSdOl4Dctp06IAXQ6AqVJ%2BcQwQlk3DYagM4G66A2N0oknTFtWGazKBXOPk%2FXsMUm4QAvaKoMWfjRaX8Cwv0CXI2UkJ5Go20ILpzqObYzzYbjoUDWvWXB9TEMuXdAZPbFytRM8o63amW169U4V4FrWWp%2Fo0zbnC0C0Bk2UdIQdd%2FIie%2FSfNJ%2BcvCdPC5XH7pQlGKVF5b1b%2B2zaobDvShWw1UBr1BzgRjJ5Cwqck7F38NuzOXflmjnRrbHMT3cC5lDtHPakzRAH%2BFeEcf8wTx41n%2FeMpnjCcCgRgc9oD1iGwbiHRdx8zXtakwUZNthuo1IXNtuxYlSh%2Fb%2FZZVn8znJIjQFPq5nln0adxsWj9wbQ1gZuj%2Fk9PvCf4b5%2B2B9n0cczsd1w%2Fwc8fodrJQQAAA%3D%3D

**Comment by g-plane** [comment]
This is a known issue. SWC can return detailed error information which we can avoid using flaky regex, but I don't have time to refactor.

**Comment by AHorak** [comment]
> SWC can return detailed error information

Thank you for the fast reply.
Can you give me a hint where i can find more information about the error details?
How can i get them?

At the moment i catch the error as an exception.
```
 try {
            result = swcWasmWeb.transformSync(codeToCompile, SwcSettings);
            Logger.Log(result);
        } catch (e) {
            Logger.Warn(e);
}
```

**Comment by g-plane** [comment]
It can be enabled via SWC options, if I remember.

**Comment by AHorak** [comment]
Have only found the **Output** Interface but nothing with error handling in the options.

```
export interface Output {
  /**
   * Transformed code
   */
  code: string;
  /**
   * Sourcemap (**not** base64 encoded)
   */
  map?: string;
}
```
I will ask in for it in  https://github.com/swc-project/swc

Tank you

**Comment by AHorak** [comment]
It looks like it is not supported :-(
https://discord.com/channels/889779439272075314/1060463406680915968
