### ISSUE TITLE
display rust structs untranslated

### ISSUE THREAD

**Issue by bmacnaughton** [swc-project/swc-playground#31]
i have been working on writing transforms in rust and, while swc-playground is helpful, i spent most of my time looking at swc source code to translate the serde-renamed output to the rust structures. it would be really useful if there was another output like AST-Rust.

I am a beginner using this, but I also spent a bit of time trying to write a visitor that would just print the rust structs but made little progress on that. If that exists somewhere just point me to it.

thanks for a great facility - my transforms are working now.

**Comment by g-plane** [comment]
It sounds that this functionality should be implemented in SWC's WebAssembly module.

**Comment by g-plane** [comment]
You can use @magic-akari 's AST viewer: https://swc-ast.vercel.app/ .
