### ISSUE TITLE
Display ctxt on spans in AST

### ISSUE THREAD

**Issue by dsherret** [swc-project/swc-playground#33]
It would be useful to display the ctxt's on spans (or have an option to do so). Right now it's always zero.

**Comment by g-plane** [comment]
@kdy1 Is this supported in SWC's WebAssembly build?

**Comment by kdy1** [comment]
I think it should be already working due to https://github.com/swc-project/swc/pull/6118

**Comment by dsherret** [comment]
Oops, you are correct. I just got confused because I put in this code, which has all `0`, which I didn't expect (but looking at the swc code I see it does do that):

```ts
export { default as a } from "./a.ts";
import b, { default as c } from "./b.ts";
```

Sorry for waste of time!
