### ISSUE TITLE
add notifications when do rebuild or save settings

### ISSUE THREAD

**Issue by hardfist** [swc-project/swc-playground#38]
It's hard for me to tell whether modified setting works or rebuild works when I change code or setttings, it would be better if we can add some notification when do code change or setting change

**Comment by g-plane** [comment]
What is "change code or settings"?

**Comment by hardfist** [comment]
![20231109-155509](https://github.com/swc-project/swc-playground/assets/8898718/778d59d1-2706-4fb8-9900-7de4d4d3731e)
you can see that when I update compress options and change code, I'm not sure whether it's rebuild result not changed or not triggering rebuild at all

**Comment by g-plane** [comment]
Are there any examples for this feature? Most playgrounds don't support this feature and I can imagine that it may look strange.

**Comment by hardfist** [comment]
maybe provide a recompile button so user can make sure it will recompile and give notification when recompile successfully

**Comment by g-plane** [comment]
That would be inconvenient, since someone must click the button once if he/she wants to inspect the result.

**Comment by hardfist** [comment]
it does not affect original behavior(rebuild when type), it's just an addition button just to make sure it recompile

**Comment by g-plane** [comment]
This will mislead users, but I will consider adding a switch.

**Comment by g-plane** [comment]
After consideration, I think "not triggering rebuild" doesn't make sense. The code will always be compiled as you change. If the output doesn't change, it means your code changes or settings change doesn't affect the compilation output.

**Comment by g-plane** [comment]
Closing this because we don't have plans on it.
