### ISSUE TITLE
Can we support `@swc/wasm-typescript`?

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc-playground#42]
https://github.com/swc-project/swc/pull/9138#issuecomment-2227157949

I want to know if you are interested in providing a playground for an extra pacakge.

**Comment by g-plane** [comment]
If there's JS entry, I can integrate it.

**Comment by magic-akari** [comment]
It's hard to handle CJS exports in a browser.

**Comment by g-plane** [comment]
Please consider providing ESM exports.
