### ISSUE TITLE
Missing transform options

### ISSUE THREAD

**Issue by robpalme** [swc-project/swc-playground#47]
https://github.com/swc-project/swc-playground/blob/d8ea7cbf8efb663bd61e36024687fc6d0a4162bd/src/swc.ts#L225

The Transform options appears to be missing:

- `verbatimModuleSyntax`
- `native_class_properties`

**Comment by g-plane** [comment]
https://swc.rs/schema.json should also be updated, but not maintained in this repository.

**Comment by robpalme** [comment]
Thanks for the commit, @g-plane

It only added one of the options, not the new one added in the latest version of SWC.

**Comment by g-plane** [comment]
That `native_class_properties` is only available for stripping TypeScript types with "transform" mode which isn't applicable for this playground.
